# Generated by Django 4.0.3 on 2022-04-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_pedido_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Codigo',
        ),
    ]
